name: Damage Calculation Test

on:
  workflow_dispatch:
    branches: [ main-2022 ]
  push:
    branches: [ main-2022 ]
    
jobs:
  build:
    
    runs-on: ubutu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js v16.14.2
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.2'
        
    - run: yarn install
    - name: Install JUnit coverage reporter
      run: yarn add --dev jest-junit
    - name: run test with JUnit as reporter
      run: npx jest --ci --runInBand --reporters=default --reporter=jest-junit
      env:
        JEST_JUNIT_OUTPUT_DIR: "./junit/test-results.xml"
    - uses: actions/upload-artifact@v2
      with:
        path: ./junit/test-results.xml
      if: always()
